package flavor

import (
	"bytes"
	"fmt"
	"strconv"
	"strings"

	"tygor.dev/tygorgen/ir"
)

// ZodFlavor generates Zod schemas from IR types.
type ZodFlavor struct {
	mini bool // true for zod-mini (import * as z from 'zod/mini')
}

func (f *ZodFlavor) Name() string {
	if f.mini {
		return "zod-mini"
	}
	return "zod"
}

func (f *ZodFlavor) FileExtension() string {
	if f.mini {
		return ".zod-mini.ts"
	}
	return ".zod.ts"
}

func (f *ZodFlavor) EmitInferredType() bool {
	return true
}

func (f *ZodFlavor) EmitPreamble(ctx *EmitContext) []byte {
	var buf bytes.Buffer
	buf.WriteString("// Code generated by tygor. DO NOT EDIT.\n\n")
	if f.mini {
		buf.WriteString("import * as z from 'zod/mini';\n\n")
	} else {
		buf.WriteString("import { z } from 'zod';\n\n")
	}
	if ctx.EmitTypes && (len(ctx.RecursiveTypes) > 0 || schemaHasConstrainedGenerics(ctx.Schema)) {
		buf.WriteString("import type * as types from './types';\n\n")
	}
	return buf.Bytes()
}

func (f *ZodFlavor) EmitType(ctx *EmitContext, typ ir.TypeDescriptor) ([]byte, error) {
	switch t := typ.(type) {
	case *ir.StructDescriptor:
		return f.emitStruct(ctx, t)
	case *ir.AliasDescriptor:
		return f.emitAlias(ctx, t)
	case *ir.EnumDescriptor:
		return f.emitEnum(ctx, t)
	default:
		return nil, nil
	}
}

// ZodSchemaExpression emits a standalone schema expression for an endpoint or
// other container position. Named schemas are resolved through ctx.SchemaPrefix.
func ZodSchemaExpression(ctx *EmitContext, typ ir.TypeDescriptor, mini bool) (string, error) {
	f := &ZodFlavor{mini: mini}
	return f.typeToZod(ctx, typ, false)
}

func (f *ZodFlavor) emitStruct(ctx *EmitContext, s *ir.StructDescriptor) ([]byte, error) {
	var buf bytes.Buffer
	typeName := ctx.TypeName(s.Name)
	schemaName := ctx.SchemaName(s.Name)
	if declaration := ctx.TypeDeclarations[s.Name]; declaration != "" {
		buf.WriteString(declaration)
		buf.WriteString("\n")
	}

	generic := len(s.TypeParameters) > 0
	returnType := f.genericSchemaReturnType(ctx, s.Name, s.TypeParameters, "output")
	inputType := f.genericSchemaReturnType(ctx, s.Name, s.TypeParameters, "input")
	extendedSchemas := make([]string, len(s.Extends))
	for i, extended := range s.Extends {
		var err error
		extendedSchemas[i], err = f.typeToZod(ctx, ir.Ref(extended.Name, extended.Package), false)
		if err != nil {
			return nil, fmt.Errorf("embedded type %s: %w", extended.Name, err)
		}
	}
	if generic {
		schemaParams, err := f.schemaTypeParameters(ctx, s.TypeParameters)
		if err != nil {
			return nil, err
		}
		buf.WriteString("export function ")
		buf.WriteString(schemaName)
		buf.WriteString(schemaParams)
		if ctx.RecursiveTypes[s.Name] {
			buf.WriteString(": ")
			buf.WriteString(f.zodTypeName())
			buf.WriteString("<")
			buf.WriteString(returnType)
			buf.WriteString(", ")
			buf.WriteString(inputType)
			buf.WriteString(">")
		}
		buf.WriteString(" {\n  const schema = ")
	} else {
		buf.WriteString(fmt.Sprintf("export const %s = ", schemaName))
	}
	for _, extendedSchema := range extendedSchemas {
		buf.WriteString("z.intersection(")
		buf.WriteString(extendedSchema)
		buf.WriteString(", ")
	}
	buf.WriteString("z.object({\n")

	for _, field := range s.Fields {
		if field.Skip {
			continue
		}

		result, err := f.emitFieldSchema(ctx, field, s.Name.Name)
		if err != nil {
			return nil, fmt.Errorf("field %s: %w", field.Name, err)
		}

		buf.WriteString(ctx.IndentStr)
		if generic {
			buf.WriteString(ctx.IndentStr)
		}
		jsonName := field.JSONName
		if jsonName == "" {
			jsonName = field.Name
		}
		buf.WriteString(strconv.Quote(jsonName))
		buf.WriteString(": ")
		buf.WriteString(result.schema)
		buf.WriteString(",")
		if result.comment != "" {
			buf.WriteString(" // ")
			buf.WriteString(result.comment)
		}
		buf.WriteString("\n")
	}

	buf.WriteString("})")
	buf.WriteString(strings.Repeat(")", len(extendedSchemas)))
	if generic {
		buf.WriteString(";\n  return schema")
		if ctx.RecursiveTypes[s.Name] {
			buf.WriteString(" as unknown as ")
			buf.WriteString(f.zodTypeName())
			buf.WriteString("<")
			buf.WriteString(returnType)
			buf.WriteString(", ")
			buf.WriteString(inputType)
			buf.WriteString(">")
		}
		buf.WriteString(";\n}\n")
	} else {
		buf.WriteString(";\n")
	}

	// Export inferred type when base types.ts is not being generated
	if !ctx.EmitTypes && ctx.TypeDeclarations[s.Name] == "" {
		buf.WriteString(fmt.Sprintf("export type %s = z.infer<typeof %s>;\n", typeName, schemaName))
	}
	buf.WriteString("\n")

	return buf.Bytes(), nil
}

// fieldSchemaResult holds the schema and optional type hint comment.
type fieldSchemaResult struct {
	schema  string
	comment string // e.g., "int32 validate:\"gte=13,lte=150\""
}

func (f *ZodFlavor) emitFieldSchema(ctx *EmitContext, field ir.FieldDescriptor, typeName string) (fieldSchemaResult, error) {
	stringEncoded := field.StringEncoded || descriptorStringEncodedNumber(ctx, field.Type)
	rules := ParseValidateTag(field.ValidateTag)
	outerRules, nestedRules, hasDive := splitDiveRules(rules)
	if hasDive {
		rules = outerRules
	}
	var err error
	rules, err = canonicalizeValidationRules(ctx, rules, field.Type, f.mini)
	if err != nil {
		return fieldSchemaResult{}, err
	}

	// Get base schema from type, tracking nullability separately
	// so we can apply validations before .nullable()
	baseSchema, _, err := f.typeToZodWithNullable(ctx, field.Type, stringEncoded)
	if err != nil {
		return fieldSchemaResult{}, err
	}
	wireSchema := ctx.Schema
	if wireSchema == nil {
		wireSchema = &ir.Schema{}
	}
	isOptional := wireSchema.FieldOptional(field)
	isNullable := wireSchema.FieldNullableWhenPresent(field)
	if hasDive {
		array, ok := resolveValidationType(ctx, field.Type).(*ir.ArrayDescriptor)
		if !ok {
			if allSkippableNestedValidators(nestedRules) {
				hasDive = false
			} else {
				return fieldSchemaResult{}, fmt.Errorf("validator composition %q is only supported on arrays and slices", "dive")
			}
		}
		if hasDive {
			nested, err := f.emitFieldSchema(ctx, ir.FieldDescriptor{
				Name:        field.Name + "Element",
				Type:        array.Element,
				ValidateTag: formatValidateRules(nestedRules),
			}, typeName)
			if err != nil {
				return fieldSchemaResult{}, err
			}
			baseSchema = f.arraySchema(array, nested.schema)
		}
	}
	if hasValidationRule(rules, "required") {
		isNullable = false
	}

	// Get type hint for the underlying type
	typeHint := f.typeHint(field.Type, stringEncoded)

	// Determine type kind for validation semantics
	isPointer := validationTypeStartsWithPointer(ctx, field.Type)
	isString := f.isPrimitiveString(ctx, field.Type) && !isPointer
	typeKind := f.getTypeKind(ctx, field.Type)
	if isPointer {
		rules = withoutValidationRule(rules, "required")
	}

	var schema string
	if f.mini {
		// Zod-mini: use .check() for validations, functional wrapping for optional/nullable
		schema, err = f.emitFieldSchemaMini(ctx, baseSchema, rules, typeKind, isNullable, isOptional, typeName, field.Name, field.Type, stringEncoded)
	} else {
		// Regular Zod: use method chaining
		schema, err = f.emitFieldSchemaRegular(ctx, baseSchema, rules, isString, isNullable, isOptional, typeName, field.Name, field.Type, stringEncoded)
	}
	if err != nil {
		return fieldSchemaResult{}, err
	}

	// Build comment from type hint and validate tag
	comment := f.buildFieldComment(typeHint, field.ValidateTag)

	return fieldSchemaResult{schema: schema, comment: comment}, nil
}

func allSkippableNestedValidators(rules []ValidateRule) bool {
	for _, rule := range rules {
		if !isSkippableNestedValidator(rule.Name) {
			return false
		}
	}
	return true
}

func splitDiveRules(rules []ValidateRule) (outer, nested []ValidateRule, found bool) {
	for i, rule := range rules {
		if rule.Name == "dive" {
			return rules[:i], rules[i+1:], true
		}
	}
	return rules, nil, false
}

func formatValidateRules(rules []ValidateRule) string {
	parts := make([]string, len(rules))
	for i, rule := range rules {
		parts[i] = rule.Name
		if rule.Param != "" {
			parts[i] += "=" + rule.Param
		}
	}
	return strings.Join(parts, ",")
}

func hasValidationRule(rules []ValidateRule, name string) bool {
	for _, rule := range rules {
		if rule.Name == name {
			return true
		}
	}
	return false
}

func withoutValidationRule(rules []ValidateRule, name string) []ValidateRule {
	result := make([]ValidateRule, 0, len(rules))
	for _, rule := range rules {
		if rule.Name != name {
			result = append(result, rule)
		}
	}
	return result
}

func validationTypeStartsWithPointer(ctx *EmitContext, typ ir.TypeDescriptor) bool {
	seen := make(map[ir.GoIdentifier]bool)
	for {
		switch typed := typ.(type) {
		case *ir.PtrDescriptor:
			return true
		case *ir.ReferenceDescriptor:
			if len(typed.TypeArguments) > 0 || ctx == nil || ctx.Schema == nil || seen[typed.Target] {
				return false
			}
			seen[typed.Target] = true
			alias, ok := ctx.Schema.FindType(typed.Target).(*ir.AliasDescriptor)
			if !ok {
				return false
			}
			typ = alias.Underlying
		default:
			return false
		}
	}
}

func (f *ZodFlavor) arraySchema(array *ir.ArrayDescriptor, element string) string {
	if array.IsSlice() {
		return fmt.Sprintf("z.array(%s)", element)
	}
	if array.Length <= 10 {
		items := make([]string, array.Length)
		for i := range items {
			items[i] = element
		}
		return fmt.Sprintf("z.tuple([%s])", strings.Join(items, ", "))
	}
	if f.mini {
		return fmt.Sprintf("z.array(%s).check(z.length(%d))", element, array.Length)
	}
	return fmt.Sprintf("z.array(%s).length(%d)", element, array.Length)
}

// emitFieldSchemaRegular generates schema using regular Zod method chaining.
func (f *ZodFlavor) emitFieldSchemaRegular(ctx *EmitContext, baseSchema string, rules []ValidateRule, isString, isNullable, isOptional bool, typeName, fieldName string, typ ir.TypeDescriptor, stringEncoded bool) (string, error) {
	var validations strings.Builder
	for _, rule := range rules {
		if method, support, handled := f.stringEncodedStringValidation(ctx, rule, typ, stringEncoded); handled {
			if support == ZodUnsupported {
				ctx.AddWarning("%s.%s: unsupported validator %q has no Zod equivalent", typeName, fieldName, rule.Name)
			}
			validations.WriteString(method)
			continue
		}
		if method, handled := lengthValidation(ctx, rule, typ, false); handled {
			validations.WriteString(method)
			continue
		}
		if rule.Name == "oneof" {
			method, err := f.oneOfValidation(ctx, rule, typ, stringEncoded)
			if err != nil {
				return "", err
			}
			validations.WriteString(method)
			continue
		}
		if stringEncoded {
			if method, handled := f.stringEncodedValidation(ctx, rule, typ); handled {
				validations.WriteString(method)
				continue
			}
		}
		if method, handled := numericLenValidation(ctx, rule, typ, false); handled {
			validations.WriteString(method)
			continue
		}
		if method, support, handled := f.namedEnumValidation(ctx, rule, typ, false); handled {
			if support == ZodUnsupported {
				ctx.AddWarning("%s.%s: unsupported validator %q has no Zod equivalent", typeName, fieldName, rule.Name)
			}
			validations.WriteString(method)
			continue
		}
		method, support := rule.ZodMethodWithSupport(isString)
		if support == ZodUnsupported {
			ctx.AddWarning("%s.%s: unsupported validator %q has no Zod equivalent",
				typeName, fieldName, rule.Name)
		}
		if method != "" && !strings.HasPrefix(method, "__ENUM__") {
			validations.WriteString(method)
		}
	}

	schema := baseSchema + validations.String()

	// Apply nullable after validations (Zod requires this order)
	if isNullable {
		schema += ".nullable()"
	}

	// Handle optionality
	if isOptional {
		schema += ".optional()"
	}

	return schema, nil
}

// emitFieldSchemaMini generates schema using zod-mini functional API.
func (f *ZodFlavor) emitFieldSchemaMini(ctx *EmitContext, baseSchema string, rules []ValidateRule, typeKind ZodMiniTypeKind, isNullable, isOptional bool, typeName, fieldName string, typ ir.TypeDescriptor, stringEncoded bool) (string, error) {
	// Collect all checks
	var checks []string
	for _, rule := range rules {
		if check, support, handled := f.stringEncodedStringValidation(ctx, rule, typ, stringEncoded); handled {
			if support == ZodUnsupported {
				ctx.AddWarning("%s.%s: unsupported validator %q has no Zod equivalent", typeName, fieldName, rule.Name)
			}
			if check != "" {
				checks = append(checks, check)
			}
			continue
		}
		if check, handled := lengthValidation(ctx, rule, typ, true); handled {
			checks = append(checks, check)
			continue
		}
		if rule.Name == "oneof" {
			check, err := f.oneOfValidation(ctx, rule, typ, stringEncoded)
			if err != nil {
				return "", err
			}
			checks = append(checks, check)
			continue
		}
		if stringEncoded {
			if check, handled := f.stringEncodedValidation(ctx, rule, typ); handled {
				checks = append(checks, check)
				continue
			}
		}
		if check, handled := numericLenValidation(ctx, rule, typ, true); handled {
			checks = append(checks, check)
			continue
		}
		if check, support, handled := f.namedEnumValidation(ctx, rule, typ, true); handled {
			if support == ZodUnsupported {
				ctx.AddWarning("%s.%s: unsupported validator %q has no Zod equivalent", typeName, fieldName, rule.Name)
			}
			if check != "" {
				checks = append(checks, check)
			}
			continue
		}
		check, support := rule.ZodMiniCheck(typeKind)
		if support == ZodUnsupported {
			ctx.AddWarning("%s.%s: unsupported validator %q has no Zod equivalent",
				typeName, fieldName, rule.Name)
		}
		if check != "" && !strings.HasPrefix(check, "__ENUM__") {
			checks = append(checks, check)
		}
	}

	schema := baseSchema

	// Apply checks if any
	if len(checks) > 0 {
		schema += ".check(" + strings.Join(checks, ", ") + ")"
	}

	// Apply nullable using functional wrapper (innermost)
	if isNullable {
		schema = fmt.Sprintf("z.nullable(%s)", schema)
	}

	// Apply optional using functional wrapper (outermost)
	if isOptional {
		schema = fmt.Sprintf("z.optional(%s)", schema)
	}

	return schema, nil
}

func (f *ZodFlavor) namedEnumValidation(ctx *EmitContext, rule ValidateRule, typ ir.TypeDescriptor, mini bool) (string, ZodSupport, bool) {
	if resolveValidationEnum(ctx, typ) == nil {
		return "", ZodSkipped, false
	}
	primitive, ok := resolveValidationType(ctx, typ).(*ir.PrimitiveDescriptor)
	if !ok {
		return "", ZodUnsupported, true
	}

	base := f.primitiveToZod(primitive, false)
	if mini {
		check, support := rule.ZodMiniCheck(f.getTypeKind(ctx, typ))
		if check == "" || strings.HasPrefix(check, "__ENUM__") {
			return "", support, true
		}
		predicate := fmt.Sprintf("v => %s.check(%s).safeParse(v).success", base, check)
		return "z.refine(" + predicate + ")", support, true
	}

	isString := primitive.PrimitiveKind == ir.PrimitiveString || primitive.PrimitiveKind == ir.PrimitiveBytes
	method, support := rule.ZodMethodWithSupport(isString)
	if method == "" || strings.HasPrefix(method, "__ENUM__") {
		return "", support, true
	}
	predicate := fmt.Sprintf("v => %s%s.safeParse(v).success", base, method)
	return ".refine(" + predicate + ")", support, true
}

// getTypeKind returns the ZodMiniTypeKind for a type descriptor.
func (f *ZodFlavor) getTypeKind(ctx *EmitContext, typ ir.TypeDescriptor) ZodMiniTypeKind {
	// Unwrap pointers
	typ = resolveValidationType(ctx, typ)

	switch t := typ.(type) {
	case *ir.PrimitiveDescriptor:
		if t.PrimitiveKind == ir.PrimitiveString || t.PrimitiveKind == ir.PrimitiveBytes {
			return ZodMiniTypeString
		}
		return ZodMiniTypeNumber
	case *ir.ArrayDescriptor, *ir.MapDescriptor:
		return ZodMiniTypeArray
	default:
		return ZodMiniTypeNumber
	}
}

func lengthValidation(ctx *EmitContext, rule ValidateRule, typ ir.TypeDescriptor, mini bool) (string, bool) {
	base := resolveValidationType(ctx, typ)
	var length string
	switch typed := base.(type) {
	case *ir.PrimitiveDescriptor:
		if typed.PrimitiveKind != ir.PrimitiveString && typed.PrimitiveKind != ir.PrimitiveBytes {
			return "", false
		}
		if rule.Name != "gt" && rule.Name != "gte" && rule.Name != "lt" && rule.Name != "lte" {
			return "", false
		}
		length = "Array.from(v).length"
	case *ir.ArrayDescriptor:
		if typed.IsSlice() && (rule.Name == "min" || rule.Name == "max" || rule.Name == "len") {
			return "", false
		}
		length = "v.length"
	case *ir.MapDescriptor:
		length = "Object.keys(v).length"
	default:
		return "", false
	}

	operator := map[string]string{
		"min": ">=", "gte": ">=", "gt": ">", "max": "<=", "lte": "<=", "lt": "<", "len": "===", "eq": "===", "ne": "!==",
	}[rule.Name]
	if operator == "" || rule.Param == "" {
		return "", false
	}
	predicate := fmt.Sprintf("v => %s %s %s", length, operator, rule.Param)
	if mini {
		return "z.refine(" + predicate + ")", true
	}
	return ".refine(" + predicate + ")", true
}

func numericLenValidation(ctx *EmitContext, rule ValidateRule, typ ir.TypeDescriptor, mini bool) (string, bool) {
	if rule.Name != "len" || rule.Param == "" {
		return "", false
	}
	primitive, ok := resolveValidationType(ctx, typ).(*ir.PrimitiveDescriptor)
	if !ok {
		return "", false
	}
	switch primitive.PrimitiveKind {
	case ir.PrimitiveInt, ir.PrimitiveUint, ir.PrimitiveFloat, ir.PrimitiveDuration:
		predicate := fmt.Sprintf("v => v === %s", rule.Param)
		if mini {
			return "z.refine(" + predicate + ")", true
		}
		return ".refine(" + predicate + ")", true
	default:
		return "", false
	}
}

func (f *ZodFlavor) stringEncodedStringValidation(ctx *EmitContext, rule ValidateRule, typ ir.TypeDescriptor, stringEncoded bool) (string, ZodSupport, bool) {
	if !stringEncoded {
		return "", ZodSkipped, false
	}
	primitive, ok := resolveValidationType(ctx, typ).(*ir.PrimitiveDescriptor)
	if !ok || primitive.PrimitiveKind != ir.PrimitiveString {
		return "", ZodSkipped, false
	}

	var schema string
	var support ZodSupport
	if check, handled := lengthValidation(ctx, rule, typ, f.mini); handled {
		if f.mini {
			schema = "z.string().check(" + check + ")"
		} else {
			schema = "z.string()" + check
		}
		support = ZodSupported
	} else if rule.Name == "oneof" {
		values := parseOneOfValues(rule.Param)
		if len(values) == 0 {
			return "", ZodUnsupported, true
		}
		quoted := make([]string, len(values))
		for i, value := range values {
			quoted[i] = strconv.Quote(value)
		}
		predicate := fmt.Sprintf("v => [%s].includes(v)", strings.Join(quoted, ", "))
		if f.mini {
			schema = "z.string().check(z.refine(" + predicate + "))"
		} else {
			schema = "z.string().refine(" + predicate + ")"
		}
		support = ZodSupported
	} else if f.mini {
		check, currentSupport := rule.ZodMiniCheck(ZodMiniTypeString)
		support = currentSupport
		if check != "" {
			schema = "z.string().check(" + check + ")"
		}
	} else {
		method, currentSupport := rule.ZodMethodWithSupport(true)
		support = currentSupport
		if method != "" && !strings.HasPrefix(method, "__ENUM__") {
			schema = "z.string()" + method
		}
	}
	if schema == "" {
		return "", support, true
	}
	predicate := fmt.Sprintf("v => { try { return %s.safeParse(JSON.parse(v)).success; } catch { return false; } }", schema)
	if f.mini {
		return "z.refine(" + predicate + ")", support, true
	}
	return ".refine(" + predicate + ")", support, true
}

// typeHint returns the Go type name for types worth documenting.
// Returns empty string for types where the Zod schema is self-explanatory.
func (f *ZodFlavor) typeHint(typ ir.TypeDescriptor, stringEncoded bool) string {
	// Unwrap pointers to get the underlying type
	for {
		if ptr, ok := typ.(*ir.PtrDescriptor); ok {
			typ = ptr.Element
		} else {
			break
		}
	}

	p, ok := typ.(*ir.PrimitiveDescriptor)
	if !ok {
		return ""
	}

	var hint string
	switch p.PrimitiveKind {
	case ir.PrimitiveInt:
		hint = f.intTypeName(p.BitSize, true)
	case ir.PrimitiveUint:
		hint = f.intTypeName(p.BitSize, false)
	case ir.PrimitiveFloat:
		if p.BitSize == 32 {
			hint = "float32"
		} else {
			hint = "float64"
		}
	case ir.PrimitiveBool:
		if stringEncoded {
			hint = "bool"
		}
	case ir.PrimitiveDuration:
		return "time.Duration (nanoseconds)"
	case ir.PrimitiveBytes:
		return "[]byte (base64)"
	default:
		return ""
	}

	if stringEncoded && hint != "" {
		return hint + ` json:",string"`
	}
	return hint
}

// intTypeName returns the Go type name for an integer.
func (f *ZodFlavor) intTypeName(bitSize int, signed bool) string {
	prefix := "int"
	if !signed {
		prefix = "uint"
	}
	if bitSize == 0 {
		return prefix // platform-dependent
	}
	return fmt.Sprintf("%s%d", prefix, bitSize)
}

// buildFieldComment constructs the trailing comment for a field.
// Format: "int32 validate:\"gte=13,lte=150\"" or just "int32" or just "validate:\"...\""
func (f *ZodFlavor) buildFieldComment(typeHint, validateTag string) string {
	if typeHint == "" && validateTag == "" {
		return ""
	}
	if typeHint != "" && validateTag != "" {
		return fmt.Sprintf("%s validate:%q", typeHint, validateTag)
	}
	if typeHint != "" {
		return typeHint
	}
	return fmt.Sprintf("validate:%q", validateTag)
}

// typeToZodWithNullable returns the Zod schema and whether it's nullable.
// This allows callers to apply validations before .nullable().
func (f *ZodFlavor) typeToZodWithNullable(ctx *EmitContext, typ ir.TypeDescriptor, stringEncoded bool) (string, bool, error) {
	nullable := false
	seen := make(map[ir.GoIdentifier]bool)
	for {
		switch t := typ.(type) {
		case *ir.PtrDescriptor:
			nullable = true
			typ = t.Element
		case *ir.ReferenceDescriptor:
			if (!stringEncoded && len(t.TypeArguments) > 0) || ctx == nil || ctx.Schema == nil || ctx.SchemaPrefix != "" || ctx.RecursiveTypes[t.Target] || seen[t.Target] {
				goto resolved
			}
			alias, ok := ctx.Schema.FindType(t.Target).(*ir.AliasDescriptor)
			if !ok {
				goto resolved
			}
			seen[t.Target] = true
			typ = alias.Underlying
		default:
			goto resolved
		}
	}

resolved:
	schema, err := f.typeToZodBase(ctx, typ, stringEncoded)
	return schema, nullable, err
}

func (f *ZodFlavor) typeToZod(ctx *EmitContext, typ ir.TypeDescriptor, stringEncoded bool) (string, error) {
	schema, nullable, err := f.typeToZodWithNullable(ctx, typ, stringEncoded)
	if err != nil || !nullable {
		return schema, err
	}
	if f.mini {
		return fmt.Sprintf("z.nullable(%s)", schema), nil
	}
	return schema + ".nullable()", nil
}

func (f *ZodFlavor) typeToZodBase(ctx *EmitContext, typ ir.TypeDescriptor, stringEncoded bool) (string, error) {
	switch t := typ.(type) {
	case *ir.PrimitiveDescriptor:
		return f.primitiveToZod(t, stringEncoded), nil

	case *ir.ArrayDescriptor:
		// StringEncoded doesn't apply to array elements
		elem, err := f.typeToZod(ctx, t.Element, false)
		if err != nil {
			return "", err
		}
		return f.arraySchema(t, elem), nil

	case *ir.MapDescriptor:
		// JSON object keys are strings even when the Go map key is numeric.
		key, err := f.mapKeyToZod(ctx, t.Key)
		if err != nil {
			return "", err
		}
		value, err := f.typeToZod(ctx, t.Value, false)
		if err != nil {
			return "", err
		}
		return fmt.Sprintf("z.record(%s, %s)", key, value), nil

	case *ir.ReferenceDescriptor:
		if stringEncoded {
			switch underlying := resolveNamedWireType(ctx, t.Target).(type) {
			case *ir.PrimitiveDescriptor:
				return f.typeToZodBase(ctx, underlying, true)
			case *ir.EnumDescriptor:
				return f.stringEncodedEnumSchema(underlying)
			}
		}
		schema := ctx.SchemaName(t.Target)
		if len(t.TypeArguments) > 0 {
			args := make([]string, len(t.TypeArguments))
			for i, arg := range t.TypeArguments {
				var err error
				args[i], err = f.typeToZod(ctx, arg, false)
				if err != nil {
					return "", err
				}
			}
			schema += "(" + strings.Join(args, ", ") + ")"
		}
		if ctx.RecursiveTypes[t.Target] {
			if len(t.TypeArguments) > 0 {
				return "z.lazy(() => " + schema + ")", nil
			}
			return f.lazyReference(ctx, t.Target, schema), nil
		}
		return schema, nil

	case *ir.UnionDescriptor:
		if len(t.Types) == 1 {
			return f.typeToZod(ctx, t.Types[0], stringEncoded)
		}
		parts := make([]string, len(t.Types))
		for i, ut := range t.Types {
			p, err := f.typeToZod(ctx, ut, stringEncoded)
			if err != nil {
				return "", err
			}
			parts[i] = p
		}
		return fmt.Sprintf("z.union([%s])", strings.Join(parts, ", ")), nil

	case *ir.TypeParameterDescriptor:
		return t.ParamName + "Schema", nil

	default:
		return "z.unknown()", nil
	}
}

func (f *ZodFlavor) zodTypeName() string {
	if f.mini {
		return "z.ZodMiniType"
	}
	return "z.ZodType"
}

func (f *ZodFlavor) schemaTypeParameters(ctx *EmitContext, params []ir.TypeParameterDescriptor) (string, error) {
	parts := make([]string, len(params))
	for i, param := range params {
		schemaConstraint := f.zodTypeName()
		if param.Constraint != nil {
			if ctx.TypeExpressionWithTypeParameters == nil {
				return "", fmt.Errorf("emit schema constraint for %s: type-parameter expression emission is not configured", param.ParamName)
			}
			outputConstraint, err := ctx.TypeExpressionWithTypeParameters(param.Constraint, func(name string) string {
				return "z.output<" + name + "Schema>"
			})
			if err != nil {
				return "", fmt.Errorf("emit output schema constraint for %s: %w", param.ParamName, err)
			}
			inputConstraint, err := ctx.TypeExpressionWithTypeParameters(param.Constraint, func(name string) string {
				return "z.input<" + name + "Schema>"
			})
			if err != nil {
				return "", fmt.Errorf("emit input schema constraint for %s: %w", param.ParamName, err)
			}
			schemaConstraint += "<" + outputConstraint + ", " + inputConstraint + ">"
		}
		parts[i] = param.ParamName + "Schema extends " + schemaConstraint
	}
	arguments := make([]string, len(params))
	for i, param := range params {
		arguments[i] = param.ParamName + "Schema: " + param.ParamName + "Schema"
	}
	return "<" + strings.Join(parts, ", ") + ">(" + strings.Join(arguments, ", ") + ")", nil
}

func schemaHasConstrainedGenerics(schema *ir.Schema) bool {
	if schema == nil {
		return false
	}
	for _, typ := range schema.Types {
		var params []ir.TypeParameterDescriptor
		switch t := typ.(type) {
		case *ir.StructDescriptor:
			params = t.TypeParameters
		case *ir.AliasDescriptor:
			params = t.TypeParameters
		}
		for _, param := range params {
			if param.Constraint != nil {
				return true
			}
		}
	}
	return false
}

func (f *ZodFlavor) genericSchemaReturnType(ctx *EmitContext, id ir.GoIdentifier, params []ir.TypeParameterDescriptor, direction string) string {
	args := make([]string, len(params))
	for i, param := range params {
		args[i] = fmt.Sprintf("z.%s<%sSchema>", direction, param.ParamName)
	}
	return ctx.DataTypeName(id) + "<" + strings.Join(args, ", ") + ">"
}

func (f *ZodFlavor) lazyReference(ctx *EmitContext, id ir.GoIdentifier, schema string) string {
	return fmt.Sprintf("z.lazy((): %s<%s> => %s)", f.zodTypeName(), ctx.DataTypeName(id), schema)
}

func (f *ZodFlavor) mapKeyToZod(ctx *EmitContext, typ ir.TypeDescriptor) (string, error) {
	for {
		ptr, ok := typ.(*ir.PtrDescriptor)
		if !ok {
			break
		}
		typ = ptr.Element
	}
	if ref, ok := typ.(*ir.ReferenceDescriptor); ok {
		if ctx != nil && ctx.Schema != nil {
			target := ctx.Schema.FindType(ref.Target)
			if alias, ok := target.(*ir.AliasDescriptor); ok {
				return f.mapKeyToZod(ctx, alias.Underlying)
			}
			if enum, ok := target.(*ir.EnumDescriptor); ok && integerEnum(enum) {
				return f.integerMapKeySchema(), nil
			}
		}
		return "z.string()", nil
	}
	primitive, ok := typ.(*ir.PrimitiveDescriptor)
	if !ok {
		return "z.string()", nil
	}
	switch primitive.PrimitiveKind {
	case ir.PrimitiveInt:
		return f.integerStringSchema(primitive, false, true), nil
	case ir.PrimitiveUint:
		return f.integerStringSchema(primitive, true, true), nil
	default:
		return "z.string()", nil
	}
}

func integerEnum(enum *ir.EnumDescriptor) bool {
	if enum == nil || len(enum.Members) == 0 {
		return false
	}
	for _, member := range enum.Members {
		if _, ok := member.Value.(int64); !ok {
			return false
		}
	}
	return true
}

func (f *ZodFlavor) integerMapKeySchema() string {
	const pattern = `[+-]?[0-9]+$(?![\s\S])`
	if f.mini {
		return fmt.Sprintf("z.string().check(z.regex(/^(?:%s)/))", pattern)
	}
	return fmt.Sprintf("z.string().regex(/^(?:%s)/)", pattern)
}

func resolveNamedWireType(ctx *EmitContext, id ir.GoIdentifier) ir.TypeDescriptor {
	if ctx == nil || ctx.Schema == nil {
		return nil
	}
	seen := make(map[ir.GoIdentifier]bool)
	typ := ctx.Schema.FindType(id)
	for {
		switch t := typ.(type) {
		case *ir.ReferenceDescriptor:
			if seen[t.Target] {
				return nil
			}
			seen[t.Target] = true
			typ = ctx.Schema.FindType(t.Target)
		case *ir.AliasDescriptor:
			typ = t.Underlying
		default:
			return typ
		}
	}
}

func (f *ZodFlavor) stringEncodedEnumSchema(enum *ir.EnumDescriptor) (string, error) {
	if len(enum.Members) == 0 {
		return "z.never()", nil
	}
	if len(enum.StringEncodedValues) == len(enum.Members) {
		values := make([]string, len(enum.StringEncodedValues))
		for i, value := range enum.StringEncodedValues {
			values[i] = strconv.Quote(value)
		}
		return "z.enum([" + strings.Join(values, ", ") + "])", nil
	}
	refine := func(base, predicate string) string {
		if f.mini {
			return base + ".check(z.refine(" + predicate + "))"
		}
		return base + ".refine(" + predicate + ")"
	}

	switch enum.Members[0].Value.(type) {
	case string:
		values := make([]string, len(enum.Members))
		for i, member := range enum.Members {
			value, ok := member.Value.(string)
			if !ok {
				return "", fmt.Errorf("enum %s has mixed wire value types", enum.Name.Name)
			}
			values[i] = strconv.Quote(value)
		}
		predicate := fmt.Sprintf(`v => { try { return [%s].includes(JSON.parse(v)); } catch { return false; } }`, strings.Join(values, ", "))
		return refine("z.string()", predicate), nil
	case int64:
		values := make([]string, len(enum.Members))
		for i, member := range enum.Members {
			value, ok := member.Value.(int64)
			if !ok {
				return "", fmt.Errorf("enum %s has mixed wire value types", enum.Name.Name)
			}
			values[i] = strconv.Quote(strconv.FormatInt(value, 10))
		}
		base := f.integerStringSchema(ir.Int(64), false, false)
		return refine(base, fmt.Sprintf(`v => { try { return [%s].includes(BigInt(v).toString()); } catch { return false; } }`, strings.Join(values, ", "))), nil
	case float64:
		values := make([]string, len(enum.Members))
		for i, member := range enum.Members {
			value, ok := member.Value.(float64)
			if !ok {
				return "", fmt.Errorf("enum %s has mixed wire value types", enum.Name.Name)
			}
			values[i] = strconv.FormatFloat(value, 'g', -1, 64)
		}
		base := f.floatStringSchema(ir.Float(64))
		return refine(base, fmt.Sprintf(`v => [%s].includes(Number(v))`, strings.Join(values, ", "))), nil
	default:
		return "", fmt.Errorf("enum %s has unsupported wire value type %T", enum.Name.Name, enum.Members[0].Value)
	}
}

func (f *ZodFlavor) oneOfValidation(ctx *EmitContext, rule ValidateRule, typ ir.TypeDescriptor, stringEncoded bool) (string, error) {
	values := parseOneOfValues(rule.Param)
	if len(values) == 0 {
		return "", fmt.Errorf("oneof requires at least one value")
	}

	base := resolveValidationType(ctx, typ)
	var predicate string
	switch t := base.(type) {
	case *ir.PrimitiveDescriptor:
		switch t.PrimitiveKind {
		case ir.PrimitiveString:
			quoted := make([]string, len(values))
			for i, value := range values {
				quoted[i] = strconv.Quote(value)
			}
			predicate = fmt.Sprintf("v => [%s].includes(v)", strings.Join(quoted, ", "))
		case ir.PrimitiveInt, ir.PrimitiveDuration:
			if stringEncoded {
				quoted := make([]string, len(values))
				for i, value := range values {
					canonical, err := canonicalInt(value, t.BitSize)
					if err != nil {
						return "", fmt.Errorf("invalid oneof integer %q: %w", value, err)
					}
					quoted[i] = strconv.Quote(canonical)
				}
				predicate = fmt.Sprintf("v => { try { return [%s].includes(BigInt(v).toString()); } catch { return false; } }", strings.Join(quoted, ", "))
			} else {
				literals := make([]string, len(values))
				for i, value := range values {
					canonical, err := canonicalInt(value, t.BitSize)
					if err != nil {
						return "", fmt.Errorf("invalid oneof integer %q: %w", value, err)
					}
					parsed, _ := strconv.ParseInt(canonical, 10, 64)
					if parsed < -9007199254740991 || parsed > 9007199254740991 {
						return "", fmt.Errorf("oneof integer %q is outside JavaScript's safe range; use json:\",string\"", value)
					}
					literals[i] = canonical
				}
				predicate = fmt.Sprintf("v => [%s].includes(v)", strings.Join(literals, ", "))
			}
		case ir.PrimitiveUint:
			if stringEncoded {
				quoted := make([]string, len(values))
				for i, value := range values {
					canonical, err := canonicalUint(value, t.BitSize)
					if err != nil {
						return "", fmt.Errorf("invalid oneof unsigned integer %q: %w", value, err)
					}
					quoted[i] = strconv.Quote(canonical)
				}
				predicate = fmt.Sprintf("v => { try { return [%s].includes(BigInt(v).toString()); } catch { return false; } }", strings.Join(quoted, ", "))
			} else {
				literals := make([]string, len(values))
				for i, value := range values {
					canonical, err := canonicalUint(value, t.BitSize)
					if err != nil {
						return "", fmt.Errorf("invalid oneof unsigned integer %q: %w", value, err)
					}
					parsed, _ := strconv.ParseUint(canonical, 10, 64)
					if parsed > 9007199254740991 {
						return "", fmt.Errorf("oneof integer %q is outside JavaScript's safe range; use json:\",string\"", value)
					}
					literals[i] = canonical
				}
				predicate = fmt.Sprintf("v => [%s].includes(v)", strings.Join(literals, ", "))
			}
		case ir.PrimitiveFloat:
			literals := make([]string, len(values))
			for i, value := range values {
				canonical, err := canonicalFloat(value, t.BitSize)
				if err != nil {
					return "", fmt.Errorf("invalid oneof float %q: %w", value, err)
				}
				literals[i] = canonical
			}
			if stringEncoded {
				predicate = fmt.Sprintf("v => [%s].includes(Number(v))", strings.Join(literals, ", "))
			} else {
				predicate = fmt.Sprintf("v => [%s].includes(v)", strings.Join(literals, ", "))
			}
		case ir.PrimitiveBool:
			quoted := make([]string, len(values))
			for i, value := range values {
				if value != "true" && value != "false" {
					return "", fmt.Errorf("invalid oneof boolean %q: expected true or false", value)
				}
				quoted[i] = strconv.Quote(value)
			}
			if stringEncoded {
				predicate = fmt.Sprintf("v => [%s].includes(v)", strings.Join(quoted, ", "))
			} else {
				predicate = fmt.Sprintf("v => [%s].includes(String(v))", strings.Join(quoted, ", "))
			}
		default:
			return "", fmt.Errorf("oneof is unsupported for %v fields", t.PrimitiveKind)
		}
	default:
		return "", fmt.Errorf("oneof is unsupported for %T fields", base)
	}

	if f.mini {
		return "z.refine(" + predicate + ")", nil
	}
	return ".refine(" + predicate + ")", nil
}

func (f *ZodFlavor) stringEncodedValidation(ctx *EmitContext, rule ValidateRule, typ ir.TypeDescriptor) (string, bool) {
	base, ok := resolveValidationType(ctx, typ).(*ir.PrimitiveDescriptor)
	if !ok {
		return "", false
	}
	operator := map[string]string{
		"min": ">=", "gte": ">=", "gt": ">", "max": "<=", "lte": "<=", "lt": "<", "len": "===", "eq": "===", "ne": "!==",
	}[rule.Name]
	if operator == "" || rule.Param == "" {
		return "", false
	}

	var predicate string
	switch base.PrimitiveKind {
	case ir.PrimitiveInt, ir.PrimitiveUint, ir.PrimitiveDuration:
		predicate = fmt.Sprintf(`v => { try { return BigInt(v) %s BigInt(%q); } catch { return false; } }`, operator, rule.Param)
	case ir.PrimitiveFloat:
		predicate = fmt.Sprintf("v => Number(v) %s %s", operator, rule.Param)
	case ir.PrimitiveBool:
		predicate = fmt.Sprintf("v => v %s %q", operator, rule.Param)
	default:
		return "", false
	}
	if f.mini {
		return "z.refine(" + predicate + ")", true
	}
	return ".refine(" + predicate + ")", true
}

func (f *ZodFlavor) primitiveToZod(p *ir.PrimitiveDescriptor, stringEncoded bool) string {
	stringEncoded = stringEncoded || p.StringEncoded
	if f.mini {
		return f.primitiveToZodMini(p, stringEncoded)
	}
	return f.primitiveToZodRegular(p, stringEncoded)
}

func descriptorStringEncodedNumber(ctx *EmitContext, typ ir.TypeDescriptor) bool {
	primitive, ok := resolveValidationType(ctx, typ).(*ir.PrimitiveDescriptor)
	return ok && primitive.StringEncoded
}

func (f *ZodFlavor) primitiveToZodRegular(p *ir.PrimitiveDescriptor, stringEncoded bool) string {
	switch p.PrimitiveKind {
	case ir.PrimitiveBool:
		if stringEncoded {
			return `z.enum(["true", "false"])`
		}
		return "z.boolean()"

	case ir.PrimitiveString:
		if stringEncoded {
			return `z.string().refine(v => { try { return typeof JSON.parse(v) === "string"; } catch { return false; } })`
		}
		return "z.string()"

	case ir.PrimitiveInt:
		if stringEncoded {
			return f.integerStringSchema(p, false, false)
		}
		return "z.number().int()" + f.intConstraints(p.BitSize)

	case ir.PrimitiveUint:
		if stringEncoded {
			return f.integerStringSchema(p, true, false)
		}
		return "z.number().int().nonnegative()" + f.uintConstraints(p.BitSize)

	case ir.PrimitiveFloat:
		if stringEncoded {
			return f.floatStringSchema(p)
		}
		return "z.number()"

	case ir.PrimitiveBytes:
		return "z.string()" // base64 encoded

	case ir.PrimitiveTime:
		return "z.string().datetime()"

	case ir.PrimitiveDuration:
		if stringEncoded {
			return f.integerStringSchema(ir.Int(64), false, false)
		}
		return "z.number().int()" // nanoseconds

	case ir.PrimitiveAny:
		return "z.unknown()"

	case ir.PrimitiveEmpty:
		return "z.object({}).strict()"

	default:
		return "z.unknown()"
	}
}

func (f *ZodFlavor) primitiveToZodMini(p *ir.PrimitiveDescriptor, stringEncoded bool) string {
	switch p.PrimitiveKind {
	case ir.PrimitiveBool:
		if stringEncoded {
			return `z.enum(["true", "false"])`
		}
		return "z.boolean()"

	case ir.PrimitiveString:
		if stringEncoded {
			return `z.string().check(z.refine(v => { try { return typeof JSON.parse(v) === "string"; } catch { return false; } }))`
		}
		return "z.string()"

	case ir.PrimitiveInt:
		if stringEncoded {
			return f.integerStringSchema(p, false, false)
		}
		base := "z.number()"
		checks := f.intChecksMini(p.BitSize, true)
		if checks != "" {
			return base + ".check(" + checks + ")"
		}
		return base

	case ir.PrimitiveUint:
		if stringEncoded {
			return f.integerStringSchema(p, true, false)
		}
		base := "z.number()"
		checks := f.uintChecksMini(p.BitSize)
		if checks != "" {
			return base + ".check(" + checks + ")"
		}
		return base

	case ir.PrimitiveFloat:
		if stringEncoded {
			return f.floatStringSchema(p)
		}
		return "z.number()"

	case ir.PrimitiveBytes:
		return "z.string()" // base64 encoded

	case ir.PrimitiveTime:
		// zod-mini uses z.iso.datetime() as a check
		return "z.string().check(z.iso.datetime())"

	case ir.PrimitiveDuration:
		if stringEncoded {
			return f.integerStringSchema(ir.Int(64), false, false)
		}
		return "z.number().check(z.int())" // nanoseconds

	case ir.PrimitiveAny:
		return "z.unknown()"

	case ir.PrimitiveEmpty:
		return "z.object({})"

	default:
		return "z.unknown()"
	}
}

func (f *ZodFlavor) integerStringSchema(p *ir.PrimitiveDescriptor, unsigned, mapKey bool) string {
	pattern := `-?[0-9]+$(?![\s\S])`
	if unsigned {
		pattern = `[0-9]+$(?![\s\S])`
	} else if mapKey {
		pattern = `[+-]?[0-9]+$(?![\s\S])`
	}
	min, max := integerBounds(p.BitSize, unsigned)
	predicate := fmt.Sprintf(`v => { try { const n = BigInt(v); return n >= BigInt(%q) && n <= BigInt(%q); } catch { return false; } }`, min, max)
	if f.mini {
		return fmt.Sprintf("z.string().check(z.regex(/^(?:%s)/), z.refine(%s))", pattern, predicate)
	}
	return fmt.Sprintf("z.string().regex(/^(?:%s)/).refine(%s)", pattern, predicate)
}

func integerBounds(bitSize int, unsigned bool) (string, string) {
	if unsigned {
		switch bitSize {
		case 8:
			return "0", "255"
		case 16:
			return "0", "65535"
		case 32:
			return "0", "4294967295"
		default:
			return "0", "18446744073709551615"
		}
	}
	switch bitSize {
	case 8:
		return "-128", "127"
	case 16:
		return "-32768", "32767"
	case 32:
		return "-2147483648", "2147483647"
	default:
		return "-9223372036854775808", "9223372036854775807"
	}
}

func (f *ZodFlavor) floatStringSchema(p *ir.PrimitiveDescriptor) string {
	predicate := "v => Number.isFinite(Number(v))"
	if p.BitSize == 32 {
		predicate = "v => Number.isFinite(Number(v)) && Number.isFinite(Math.fround(Number(v)))"
	}
	pattern := `-?(?:0|[1-9][0-9]*)(?:\.[0-9]+)?(?:[eE][+-]?[0-9]+)?$(?![\s\S])`
	if f.mini {
		return fmt.Sprintf("z.string().check(z.regex(/^(?:%s)/), z.refine(%s))", pattern, predicate)
	}
	return fmt.Sprintf("z.string().regex(/^(?:%s)/).refine(%s)", pattern, predicate)
}

// intConstraints returns regular Zod method chain for int bounds.
func (f *ZodFlavor) intConstraints(bitSize int) string {
	switch bitSize {
	case 8:
		return ".min(-128).max(127)"
	case 16:
		return ".min(-32768).max(32767)"
	case 32:
		return ".min(-2147483648).max(2147483647)"
	case 64:
		// JS number can't represent full int64 range precisely
		return ".min(-9007199254740991).max(9007199254740991)"
	default:
		return ""
	}
}

// uintConstraints returns regular Zod method chain for uint bounds.
func (f *ZodFlavor) uintConstraints(bitSize int) string {
	switch bitSize {
	case 8:
		return ".max(255)"
	case 16:
		return ".max(65535)"
	case 32:
		return ".max(4294967295)"
	case 64:
		// JS number can't represent full uint64 range precisely
		return ".max(9007199254740991)"
	default:
		return ""
	}
}

// intChecksMini returns zod-mini check functions for signed int bounds.
func (f *ZodFlavor) intChecksMini(bitSize int, signed bool) string {
	switch bitSize {
	case 8:
		return "z.int(), z.gte(-128), z.lte(127)"
	case 16:
		return "z.int(), z.gte(-32768), z.lte(32767)"
	case 32:
		return "z.int(), z.gte(-2147483648), z.lte(2147483647)"
	case 64:
		// JS number can't represent full int64 range precisely
		return "z.int(), z.gte(-9007199254740991), z.lte(9007199254740991)"
	default:
		return "z.int()"
	}
}

// uintChecksMini returns zod-mini check functions for unsigned int bounds.
func (f *ZodFlavor) uintChecksMini(bitSize int) string {
	switch bitSize {
	case 8:
		return "z.int(), z.gte(0), z.lte(255)"
	case 16:
		return "z.int(), z.gte(0), z.lte(65535)"
	case 32:
		return "z.int(), z.gte(0), z.lte(4294967295)"
	case 64:
		// JS number can't represent full uint64 range precisely
		return "z.int(), z.gte(0), z.lte(9007199254740991)"
	default:
		return "z.int(), z.gte(0)"
	}
}

func (f *ZodFlavor) isPrimitiveString(ctx *EmitContext, typ ir.TypeDescriptor) bool {
	if p, ok := resolveValidationType(ctx, typ).(*ir.PrimitiveDescriptor); ok {
		return p.PrimitiveKind == ir.PrimitiveString
	}
	return false
}

func (f *ZodFlavor) emitAlias(ctx *EmitContext, a *ir.AliasDescriptor) ([]byte, error) {
	if ctx.Schema.HasPointerOnlyAliasCycle(a) {
		return nil, fmt.Errorf("recursive pointer-only alias %s cannot be represented safely in Zod", a.Name.Name)
	}

	var buf bytes.Buffer
	typeName := ctx.TypeName(a.Name)
	schemaName := ctx.SchemaName(a.Name)
	if declaration := ctx.TypeDeclarations[a.Name]; declaration != "" {
		buf.WriteString(declaration)
		buf.WriteString("\n")
	}

	underlying, err := f.typeToZod(ctx, a.Underlying, false)
	if err != nil {
		return nil, err
	}

	if len(a.TypeParameters) > 0 {
		schemaParams, err := f.schemaTypeParameters(ctx, a.TypeParameters)
		if err != nil {
			return nil, err
		}
		buf.WriteString("export function ")
		buf.WriteString(schemaName)
		buf.WriteString(schemaParams)
		returnType := f.genericSchemaReturnType(ctx, a.Name, a.TypeParameters, "output")
		inputType := f.genericSchemaReturnType(ctx, a.Name, a.TypeParameters, "input")
		if ctx.RecursiveTypes[a.Name] {
			buf.WriteString(": ")
			buf.WriteString(f.zodTypeName())
			buf.WriteString("<" + returnType + ", " + inputType + ">")
		}
		buf.WriteString(" {\n  return ")
		buf.WriteString(underlying)
		if ctx.RecursiveTypes[a.Name] {
			buf.WriteString(" as unknown as ")
			buf.WriteString(f.zodTypeName())
			buf.WriteString("<" + returnType + ", " + inputType + ">")
		}
		buf.WriteString(";\n}\n")
	} else {
		buf.WriteString(fmt.Sprintf("export const %s = %s;\n", schemaName, underlying))
	}

	if !ctx.EmitTypes && ctx.TypeDeclarations[a.Name] == "" {
		buf.WriteString(fmt.Sprintf("export type %s = z.infer<typeof %s>;\n", typeName, schemaName))
	}
	buf.WriteString("\n")

	return buf.Bytes(), nil
}

func (f *ZodFlavor) emitEnum(ctx *EmitContext, e *ir.EnumDescriptor) ([]byte, error) {
	var buf bytes.Buffer
	typeName := ctx.TypeName(e.Name)
	schemaName := ctx.SchemaName(e.Name)

	if len(e.StringEncodedValues) == len(e.Members) && len(e.Members) > 0 {
		values := make([]string, len(e.StringEncodedValues))
		for i, value := range e.StringEncodedValues {
			values[i] = strconv.Quote(value)
		}
		buf.WriteString(fmt.Sprintf("export const %s = z.enum([%s]);\n", schemaName, strings.Join(values, ", ")))
		if !ctx.EmitTypes {
			buf.WriteString(fmt.Sprintf("export type %s = z.infer<typeof %s>;\n", typeName, schemaName))
		}
		buf.WriteString("\n")
		return buf.Bytes(), nil
	}

	// Collect ordinary member values.
	values := make([]string, 0, len(e.Members))
	for _, m := range e.Members {
		switch v := m.Value.(type) {
		case string:
			values = append(values, fmt.Sprintf("%q", v))
		case int64:
			values = append(values, fmt.Sprintf("%d", v))
		case float64:
			values = append(values, fmt.Sprintf("%v", v))
		}
	}

	if len(values) > 0 {
		// Check if all values are strings
		allStrings := true
		for _, m := range e.Members {
			if _, ok := m.Value.(string); !ok {
				allStrings = false
				break
			}
		}

		if allStrings {
			buf.WriteString(fmt.Sprintf("export const %s = z.enum([%s]);\n", schemaName, strings.Join(values, ", ")))
		} else {
			// Numeric enum - use union of literals
			literals := make([]string, len(values))
			for i, v := range values {
				literals[i] = fmt.Sprintf("z.literal(%s)", v)
			}
			buf.WriteString(fmt.Sprintf("export const %s = z.union([%s]);\n", schemaName, strings.Join(literals, ", ")))
		}
	} else {
		buf.WriteString(fmt.Sprintf("export const %s = z.never();\n", schemaName))
	}

	if !ctx.EmitTypes {
		buf.WriteString(fmt.Sprintf("export type %s = z.infer<typeof %s>;\n", typeName, schemaName))
	}
	buf.WriteString("\n")

	return buf.Bytes(), nil
}
