// Code generated by tygor. DO NOT EDIT.

import type * as types from "./types";

export interface Manifest {
  "Devtools.GetDiscovery": {
    req: Record<string, never>;
    res: (types.GetDiscoveryResponse | null);
  };
  "Devtools.GetSource": {
    req: types.GetSourceRequest;
    res: (types.GetSourceResponse | null);
  };
  "Devtools.GetStatus": {
    req: Record<string, never>;
    res: (types.GetStatusResponse | null);
    primitive: "stream";
  };
  "Devtools.Reload": {
    req: types.ReloadRequest;
    res: (types.ReloadResponse | null);
  };
  "Devtools.UpdateStatus": {
    req: types.UpdateStatusRequest;
    res: (types.UpdateStatusResponse | null);
  };
}

const metadata = {
  "Devtools.GetDiscovery": { path: "/Devtools/GetDiscovery", primitive: "query" },
  "Devtools.GetSource": { path: "/Devtools/GetSource", primitive: "query" },
  "Devtools.GetStatus": { path: "/Devtools/GetStatus", primitive: "stream" },
  "Devtools.Reload": { path: "/Devtools/Reload", primitive: "exec" },
  "Devtools.UpdateStatus": { path: "/Devtools/UpdateStatus", primitive: "exec" },
} as const;

export const registry = {
  manifest: {} as Manifest,
  metadata,
};
