// Code generated by tygor. DO NOT EDIT.

/**
 * AppStatus represents the status of the user's app as reported by vite plugin.
 * @see tygor.dev/cmd/tygor/internal/dev/dev.go#AppStatus
 */
export interface AppStatus {
  status: string;
  port?: number /* int */;
  error?: string;
  phase?: string;
}
/**
 * DiscoverySchema is the top-level discovery.json structure.
 * @see tygor.dev/cmd/tygor/internal/dev/schema.go#DiscoverySchema
 */
export interface DiscoverySchema {
  Package: PackageInfo;
  Types: TypeDescriptor[] | null;
  Services: ServiceDescriptor[] | null;
  Warnings?: Warning[] | null;
}
/**
 * Documentation holds doc comments.
 * @see tygor.dev/cmd/tygor/internal/dev/schema.go#Documentation
 */
export interface Documentation {
  Summary?: string;
  Body?: string;
  Deprecated?: string | null;
}
/**
 * EndpointDescriptor describes an RPC endpoint.
 * @see tygor.dev/cmd/tygor/internal/dev/schema.go#EndpointDescriptor
 */
export interface EndpointDescriptor {
  name: string;
  fullName: string;
  primitive: string;
  path: string;
  request?: TypeRef | null;
  response?: TypeRef | null;
  doc?: string;
}
/**
 * EnumMember describes a single enum constant.
 * @see tygor.dev/cmd/tygor/internal/dev/schema.go#EnumMember
 */
export interface EnumMember {
  name: string;
  value: unknown;
  doc?: string;
}
/**
 * FieldDescriptor describes a struct field.
 * @see tygor.dev/cmd/tygor/internal/dev/schema.go#FieldDescriptor
 */
export interface FieldDescriptor {
  name: string;
  "type": TypeRef;
  jsonName: string;
  optional?: boolean;
  stringEncoded?: boolean;
  skip?: boolean;
  validateTag?: string;
  doc?: string;
}
/**
 * GetDiscoveryRequest is the request for Devtools.GetDiscovery.
 * @see tygor.dev/cmd/tygor/internal/dev/dev.go#GetDiscoveryRequest
 */
export interface GetDiscoveryRequest {
}
/**
 * GetDiscoveryResponse returns the discovery.json content.
 * @see tygor.dev/cmd/tygor/internal/dev/dev.go#GetDiscoveryResponse
 */
export interface GetDiscoveryResponse {
  /** Discovery is the parsed discovery schema. */
  discovery: DiscoverySchema;
}
/**
 * GetSourceRequest is the request for Devtools.GetSource.
 * @see tygor.dev/cmd/tygor/internal/dev/dev.go#GetSourceRequest
 */
export interface GetSourceRequest {
  file: string;
  line?: number /* int */;
  context?: number /* int */;
}
/**
 * GetSourceResponse returns source code with context.
 * @see tygor.dev/cmd/tygor/internal/dev/dev.go#GetSourceResponse
 */
export interface GetSourceResponse {
  file: string;
  language: string;
  lines: SourceLine[] | null;
  context: number /* int */;
}
/**
 * GetStatusRequest is the request for Devtools.GetStatus.
 * @see tygor.dev/cmd/tygor/internal/dev/dev.go#GetStatusRequest
 */
export interface GetStatusRequest {
}
/**
 * GetStatusResponse returns the combined status in flat format for the devtools UI.
 * Status is a discriminated union: "ok", "error", "reloading", "starting", "disconnected".
 * @see tygor.dev/cmd/tygor/internal/dev/dev.go#GetStatusResponse
 */
export interface GetStatusResponse {
  status: string;
  port?: number /* int */;
  error?: string;
  phase?: string;
  command: string | null;
  cwd?: string;
  exitCode: number /* int */ | null;
  rawrData?: string[] | null;
}
/**
 * GoIdentifier is a fully-qualified Go type name.
 * @see tygor.dev/cmd/tygor/internal/dev/schema.go#GoIdentifier
 */
export interface GoIdentifier {
  name: string;
  "package"?: string;
}
/**
 * PackageInfo describes the source Go package.
 * @see tygor.dev/cmd/tygor/internal/dev/schema.go#PackageInfo
 */
export interface PackageInfo {
  Path: string;
  Name: string;
  Dir: string;
}
/**
 * ReloadRequest triggers a reload of discovery.json.
 * @see tygor.dev/cmd/tygor/internal/dev/dev.go#ReloadRequest
 */
export interface ReloadRequest {
  files?: string[] | null;
  reason?: string;
}
/**
 * ReloadResponse is the response for Reload.
 * @see tygor.dev/cmd/tygor/internal/dev/dev.go#ReloadResponse
 */
export interface ReloadResponse {
}
/**
 * ServiceDescriptor describes a service and its endpoints.
 * @see tygor.dev/cmd/tygor/internal/dev/schema.go#ServiceDescriptor
 */
export interface ServiceDescriptor {
  name: string;
  endpoints: EndpointDescriptor[] | null;
  doc?: string;
}
/**
 * SourceLine represents a single line of source code.
 * @see tygor.dev/cmd/tygor/internal/dev/dev.go#SourceLine
 */
export interface SourceLine {
  num: number /* int */;
  content: string;
  highlight?: boolean;
}
/**
 * SourceLocation points to a position in source code.
 * @see tygor.dev/cmd/tygor/internal/dev/schema.go#SourceLocation
 */
export interface SourceLocation {
  File: string;
  Line: number /* int */;
  Column: number /* int */;
}
/**
 * TypeDescriptor is a named type (struct, enum, or alias).
 * Uses kind discriminator for polymorphism.
 * @see tygor.dev/cmd/tygor/internal/dev/schema.go#TypeDescriptor
 */
export interface TypeDescriptor {
  kind: string;
  Name: GoIdentifier;
  TypeParameters?: TypeParameter[] | null;
  Fields?: FieldDescriptor[] | null;
  Members?: EnumMember[] | null;
  Underlying?: TypeRef | null;
  Extends?: GoIdentifier[] | null;
  Documentation?: Documentation | null;
  Source?: SourceLocation | null;
}
/**
 * TypeParameter describes a generic type parameter.
 * @see tygor.dev/cmd/tygor/internal/dev/schema.go#TypeParameter
 */
export interface TypeParameter {
  kind: string;
  paramName: string;
  constraint?: TypeRef | null;
}
/**
 * TypeRef is a reference to a type (used in fields, requests, responses).
 * Uses kind discriminator for the various type expression forms.
 * @see tygor.dev/cmd/tygor/internal/dev/schema.go#TypeRef
 */
export interface TypeRef {
  kind: string;
  primitiveKind?: string;
  bitSize?: number /* int */;
  name?: string;
  "package"?: string;
  element?: TypeRef | null;
  length?: number /* int */;
  key?: TypeRef | null;
  value?: TypeRef | null;
  types?: TypeRef[] | null;
  paramName?: string;
  constraint?: TypeRef | null;
}
/**
 * UpdateStatusRequest is sent by vite plugin to update app status.
 * @see tygor.dev/cmd/tygor/internal/dev/dev.go#UpdateStatusRequest
 */
export interface UpdateStatusRequest {
  app: AppStatus;
}
/**
 * UpdateStatusResponse is the response for UpdateStatus.
 * @see tygor.dev/cmd/tygor/internal/dev/dev.go#UpdateStatusResponse
 */
export interface UpdateStatusResponse {
}
/**
 * Warning represents a non-fatal issue during schema generation.
 * @see tygor.dev/cmd/tygor/internal/dev/schema.go#Warning
 */
export interface Warning {
  code: string;
  message: string;
}
